# Generated by Django 3.2.12 on 2022-03-01 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=14)),
                ('password', models.CharField(max_length=20)),
                ('doc', models.CharField(choices=[('pan', 'PAN Card '), ('aadhar', 'AAdhar Card')], max_length=20)),
                ('doc_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('verify', models.BooleanField(default=False)),
                ('pic', models.FileField(default='1.png', upload_to='profile')),
            ],
        ),
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=50)),
                ('totalseat', models.IntegerField(default=0)),
                ('availableseat', models.IntegerField(default=0)),
                ('startpoint', models.CharField(choices=[('surat', 'Surat'), ('amreli', 'Amreli')], max_length=50)),
                ('destination', models.CharField(choices=[('surat', 'Surat'), ('amreli', 'Amreli')], max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('pic', models.FileField(blank=True, null=True, upload_to='carpic')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.owner')),
            ],
        ),
    ]
