# Generated by Django 3.2.12 on 2022-03-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0006_auto_20220310_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='city',
            new_name='destination',
        ),
        migrations.AddField(
            model_name='car',
            name='startpoint',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to='pic'),
        ),
    ]
