# Generated by Django 3.2.12 on 2022-03-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0007_auto_20220311_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='startpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='city',
            new_name='destination',
        ),
    ]
