# Generated by Django 3.2.12 on 2022-03-04 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
