# Generated by Django 3.2.12 on 2022-03-05 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
