# Generated by Django 3.2.12 on 2022-03-06 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='passenger',
        ),
    ]
