# Generated by Django 3.2.12 on 2022-03-06 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_rename_passenger_passengers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='passengers',
            new_name='passenger',
        ),
    ]
