# Generated by Django 3.2.12 on 2022-03-07 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_rename_passengers_passenger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='add',
            new_name='address',
        ),
    ]
