# Generated by Django 3.2.12 on 2022-03-09 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_rename_add_passenger_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='passenger',
            new_name='user',
        ),
    ]
