# Generated by Django 3.2.12 on 2022-03-09 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_rename_passenger_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='passenger',
        ),
    ]
