# Generated by Django 3.2.12 on 2022-03-16 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0008_auto_20220311_1420'),
        ('user', '0014_rename_user_passenger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ManyToManyField(related_name='cart', to='owner.car')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_id', models.CharField(blank=True, max_length=50, null=True)),
                ('pay_method', models.BooleanField(default=True)),
                ('journydate', models.DateField()),
                ('feedback', models.TextField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.car')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.passenger')),
            ],
        ),
    ]
