# Generated by Django 3.2.12 on 2022-03-18 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0008_auto_20220311_1420'),
        ('user', '0016_auto_20220316_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ManyToManyField(related_name='cart', to='owner.car')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.passenger')),
            ],
        ),
    ]
