# Generated by Django 3.2.12 on 2022-03-27 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='car',
            new_name='Car',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='passenger',
            new_name='Passenger',
        ),
    ]
