# Generated by Django 3.2.12 on 2022-03-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_book_bookingseat'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='amount',
            field=models.IntegerField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='bookingseat',
            field=models.CharField(max_length=50),
        ),
    ]
