# Generated by Django 3.2.12 on 2022-03-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20220328_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookingseat',
            field=models.IntegerField(default=0),
        ),
    ]
